export const routes = {
  home: "/",
  login: "/login",
  dashboard: "dashboard",
  centroFormacion: "/centroFormacion",
  sedes: "/sedes",
  bodegas: "/bodegas",
  areas: "/areas",
  ambientes: "/ambientes",
  programas: "/programas",
  ciudades: "/ciudad",
  fichas: "/fichas",
  usuarios: "/usuarios",
  materiales: "/materiales",
  movimientos: "/movimientos",
  root: "..",
};
