export const routes = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  centroFormacion: "/centroFormacion",
  sedes: "/sedes",
  bodegas: "/bodegas",
  materiales: "/bodegas/:id/materiales",
  areas: "/areas",
  ambientes: "/ambientes",
  programas: "/programas",
  cargos: "/cargos",
  roles: "/roles",
  ciudades: "/ciudad",
  categorias: "/categoria",
  estadisticas: "/estadisticas",
  fichas: "/fichas",
  usuarios: "/usuarios",
  movimientos: "/movimientos",
  root: "..",
};
